name: Perf Action
description: A GitHub Action that performs a specific task using a Docker Image
author: P10-ai
branding:
  icon: activity
  color: blue
      
inputs:
  url:
    description: Open API Spec File
    required: true
  basePath:
    description: Environment used for performance run
    required: true
  authUrl:
    description: Auth url
    required: true
  authBody:
    description: Body used authentication
    required: true
    
outputs:
  report:
    description: Display performance report

runs:
  using: 'docker'
  image: 'docker://ghcr.io/p10-ai/perf-engine:main'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.basePath }}
    - ${{ inputs.authUrl }}
    - ${{ inputs.authBody }}
#   image: 'P10-ai/Perf-Engine2:main'


# runs:
#   using: 'docker'
#   image: 'ghcr.io/P10-ai/Perf-Engine2:main'  
#   image: docker://docker.pkg.github.com/P10-ai/Perf-Engine/perf-engine:latest 
