name: PerfAI, Inc.
description: A GitHub Action that performs a specific task using a Docker Image
author: P10-ai
branding:
  icon: activity
  color: blue
      
inputs:
  apiSpecURL:
    description: Open API Spec File
    required: true
  apiBasePath:
    description: Environment used for performance run
    required: true
  authUrl:
    description: Auth url
    required: true
  authBody:
    description: Body for authentication endpoint
    required: true
    
outputs:
  report:
    description: Display performance report

runs:
  using: 'docker'
  image: 'docker://ghcr.io/p10-ai/perf-engine:main'
  args:
    - ${{ inputs.apiSpecURL }}
    - ${{ inputs.apiBasePath }}
    - ${{ inputs.authUrl }}
    - ${{ inputs.authBody }}
    
