name: PerfAI Action
description: Active Performance for APIs (public, mobile, & web)
author: PerfAI, Inc.
branding:
  icon: activity
  color: blue
      
inputs:
  apiSpecURL:
    description: OpenAPI-Specification/Swagger URL
    required: true
  apiBasePath:
    description: API Base Path
    required: true
  authUrl:
    description: Token Authentication URL
    required: true
  authBody:
    description: Authentication Body JSON/Data
    required: true
    
outputs:
  report:
    description: Displays performance report

runs:
  using: 'docker'
  image: 'docker://ghcr.io/perfai-inc/perfai-engine:main'
  args:
    - ${{ inputs.apiSpecURL }}
    - ${{ inputs.apiBasePath }}
    - ${{ inputs.authUrl }}
    - ${{ inputs.authBody }}
    
